/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRatesRouteImport } from './routes/customer-rates'
import { Route as CustomerBalancesRouteImport } from './routes/customer-balances'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsIndexRouteImport } from './routes/records/index'
import { Route as LedgerIndexRouteImport } from './routes/ledger/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as BillsIndexRouteImport } from './routes/bills/index'
import { Route as RecordsNewRouteImport } from './routes/records/new'
import { Route as RecordsRecordIdRouteImport } from './routes/records/$recordId'
import { Route as LedgerNewRouteImport } from './routes/ledger/new'
import { Route as InventoryUpdateRouteImport } from './routes/inventory/update'
import { Route as CustomersUnbilledRouteImport } from './routes/customers/unbilled'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as BillsNewRouteImport } from './routes/bills/new'
import { Route as BillsBillIdRouteImport } from './routes/bills/$billId'
import { Route as RecordsUpdateRecordIdRouteImport } from './routes/records/update.$recordId'
import { Route as CustomersUpdateCustomerIdRouteImport } from './routes/customers/update.$customerId'
import { Route as CustomersStatementCustomerIdRouteImport } from './routes/customers/statement.$customerId'
import { Route as BillsPrintBillIdRouteImport } from './routes/bills/print.$billId'

const CustomerRatesRoute = CustomerRatesRouteImport.update({
  id: '/customer-rates',
  path: '/customer-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBalancesRoute = CustomerBalancesRouteImport.update({
  id: '/customer-balances',
  path: '/customer-balances',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsNewRoute = RecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRecordIdRoute = RecordsRecordIdRouteImport.update({
  id: '/records/$recordId',
  path: '/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerNewRoute = LedgerNewRouteImport.update({
  id: '/ledger/new',
  path: '/ledger/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryUpdateRoute = InventoryUpdateRouteImport.update({
  id: '/inventory/update',
  path: '/inventory/update',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersUnbilledRoute = CustomersUnbilledRouteImport.update({
  id: '/customers/unbilled',
  path: '/customers/unbilled',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdRoute = BillsBillIdRouteImport.update({
  id: '/bills/$billId',
  path: '/bills/$billId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsUpdateRecordIdRoute = RecordsUpdateRecordIdRouteImport.update({
  id: '/records/update/$recordId',
  path: '/records/update/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersUpdateCustomerIdRoute =
  CustomersUpdateCustomerIdRouteImport.update({
    id: '/customers/update/$customerId',
    path: '/customers/update/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersStatementCustomerIdRoute =
  CustomersStatementCustomerIdRouteImport.update({
    id: '/customers/statement/$customerId',
    path: '/customers/statement/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BillsPrintBillIdRoute = BillsPrintBillIdRouteImport.update({
  id: '/bills/print/$billId',
  path: '/bills/print/$billId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer-balances': typeof CustomerBalancesRoute
  '/customer-rates': typeof CustomerRatesRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills/new': typeof BillsNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/unbilled': typeof CustomersUnbilledRoute
  '/inventory/update': typeof InventoryUpdateRoute
  '/ledger/new': typeof LedgerNewRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/records/new': typeof RecordsNewRoute
  '/bills': typeof BillsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/ledger': typeof LedgerIndexRoute
  '/records': typeof RecordsIndexRoute
  '/bills/print/$billId': typeof BillsPrintBillIdRoute
  '/customers/statement/$customerId': typeof CustomersStatementCustomerIdRoute
  '/customers/update/$customerId': typeof CustomersUpdateCustomerIdRoute
  '/records/update/$recordId': typeof RecordsUpdateRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-balances': typeof CustomerBalancesRoute
  '/customer-rates': typeof CustomerRatesRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills/new': typeof BillsNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/unbilled': typeof CustomersUnbilledRoute
  '/inventory/update': typeof InventoryUpdateRoute
  '/ledger/new': typeof LedgerNewRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/records/new': typeof RecordsNewRoute
  '/bills': typeof BillsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/ledger': typeof LedgerIndexRoute
  '/records': typeof RecordsIndexRoute
  '/bills/print/$billId': typeof BillsPrintBillIdRoute
  '/customers/statement/$customerId': typeof CustomersStatementCustomerIdRoute
  '/customers/update/$customerId': typeof CustomersUpdateCustomerIdRoute
  '/records/update/$recordId': typeof RecordsUpdateRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer-balances': typeof CustomerBalancesRoute
  '/customer-rates': typeof CustomerRatesRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills/new': typeof BillsNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/unbilled': typeof CustomersUnbilledRoute
  '/inventory/update': typeof InventoryUpdateRoute
  '/ledger/new': typeof LedgerNewRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/records/new': typeof RecordsNewRoute
  '/bills/': typeof BillsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/bills/print/$billId': typeof BillsPrintBillIdRoute
  '/customers/statement/$customerId': typeof CustomersStatementCustomerIdRoute
  '/customers/update/$customerId': typeof CustomersUpdateCustomerIdRoute
  '/records/update/$recordId': typeof RecordsUpdateRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer-balances'
    | '/customer-rates'
    | '/bills/$billId'
    | '/bills/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/customers/unbilled'
    | '/inventory/update'
    | '/ledger/new'
    | '/records/$recordId'
    | '/records/new'
    | '/bills'
    | '/customers'
    | '/inventory'
    | '/ledger'
    | '/records'
    | '/bills/print/$billId'
    | '/customers/statement/$customerId'
    | '/customers/update/$customerId'
    | '/records/update/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-balances'
    | '/customer-rates'
    | '/bills/$billId'
    | '/bills/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/customers/unbilled'
    | '/inventory/update'
    | '/ledger/new'
    | '/records/$recordId'
    | '/records/new'
    | '/bills'
    | '/customers'
    | '/inventory'
    | '/ledger'
    | '/records'
    | '/bills/print/$billId'
    | '/customers/statement/$customerId'
    | '/customers/update/$customerId'
    | '/records/update/$recordId'
  id:
    | '__root__'
    | '/'
    | '/customer-balances'
    | '/customer-rates'
    | '/bills/$billId'
    | '/bills/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/customers/unbilled'
    | '/inventory/update'
    | '/ledger/new'
    | '/records/$recordId'
    | '/records/new'
    | '/bills/'
    | '/customers/'
    | '/inventory/'
    | '/ledger/'
    | '/records/'
    | '/bills/print/$billId'
    | '/customers/statement/$customerId'
    | '/customers/update/$customerId'
    | '/records/update/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerBalancesRoute: typeof CustomerBalancesRoute
  CustomerRatesRoute: typeof CustomerRatesRoute
  BillsBillIdRoute: typeof BillsBillIdRoute
  BillsNewRoute: typeof BillsNewRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersUnbilledRoute: typeof CustomersUnbilledRoute
  InventoryUpdateRoute: typeof InventoryUpdateRoute
  LedgerNewRoute: typeof LedgerNewRoute
  RecordsRecordIdRoute: typeof RecordsRecordIdRoute
  RecordsNewRoute: typeof RecordsNewRoute
  BillsIndexRoute: typeof BillsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
  BillsPrintBillIdRoute: typeof BillsPrintBillIdRoute
  CustomersStatementCustomerIdRoute: typeof CustomersStatementCustomerIdRoute
  CustomersUpdateCustomerIdRoute: typeof CustomersUpdateCustomerIdRoute
  RecordsUpdateRecordIdRoute: typeof RecordsUpdateRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer-rates': {
      id: '/customer-rates'
      path: '/customer-rates'
      fullPath: '/customer-rates'
      preLoaderRoute: typeof CustomerRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-balances': {
      id: '/customer-balances'
      path: '/customer-balances'
      fullPath: '/customer-balances'
      preLoaderRoute: typeof CustomerBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/new': {
      id: '/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof RecordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$recordId': {
      id: '/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/records/$recordId'
      preLoaderRoute: typeof RecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/new': {
      id: '/ledger/new'
      path: '/ledger/new'
      fullPath: '/ledger/new'
      preLoaderRoute: typeof LedgerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/update': {
      id: '/inventory/update'
      path: '/inventory/update'
      fullPath: '/inventory/update'
      preLoaderRoute: typeof InventoryUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/unbilled': {
      id: '/customers/unbilled'
      path: '/customers/unbilled'
      fullPath: '/customers/unbilled'
      preLoaderRoute: typeof CustomersUnbilledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId': {
      id: '/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof BillsBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/update/$recordId': {
      id: '/records/update/$recordId'
      path: '/records/update/$recordId'
      fullPath: '/records/update/$recordId'
      preLoaderRoute: typeof RecordsUpdateRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/update/$customerId': {
      id: '/customers/update/$customerId'
      path: '/customers/update/$customerId'
      fullPath: '/customers/update/$customerId'
      preLoaderRoute: typeof CustomersUpdateCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/statement/$customerId': {
      id: '/customers/statement/$customerId'
      path: '/customers/statement/$customerId'
      fullPath: '/customers/statement/$customerId'
      preLoaderRoute: typeof CustomersStatementCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/print/$billId': {
      id: '/bills/print/$billId'
      path: '/bills/print/$billId'
      fullPath: '/bills/print/$billId'
      preLoaderRoute: typeof BillsPrintBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerBalancesRoute: CustomerBalancesRoute,
  CustomerRatesRoute: CustomerRatesRoute,
  BillsBillIdRoute: BillsBillIdRoute,
  BillsNewRoute: BillsNewRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  CustomersUnbilledRoute: CustomersUnbilledRoute,
  InventoryUpdateRoute: InventoryUpdateRoute,
  LedgerNewRoute: LedgerNewRoute,
  RecordsRecordIdRoute: RecordsRecordIdRoute,
  RecordsNewRoute: RecordsNewRoute,
  BillsIndexRoute: BillsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LedgerIndexRoute: LedgerIndexRoute,
  RecordsIndexRoute: RecordsIndexRoute,
  BillsPrintBillIdRoute: BillsPrintBillIdRoute,
  CustomersStatementCustomerIdRoute: CustomersStatementCustomerIdRoute,
  CustomersUpdateCustomerIdRoute: CustomersUpdateCustomerIdRoute,
  RecordsUpdateRecordIdRoute: RecordsUpdateRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
